services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: kudwa
      POSTGRES_PASSWORD: kudwa
      POSTGRES_DB: kudwadb
    ports: ["5437:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
  
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile    
    ports:
      - "8430:8430"  # Backend API port
      - "8431:8431"  # Streamlit frontend port
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://kudwa:kudwa@db:5432/kudwadb
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs  # Mount logs directory for persistence
    command: ["./run_all.sh"]

volumes:
  db_data: